# Site settings
title: "David Calvo Meier"
description: "Programador y Director"

# Resume settings
resume_name: David Calvo Meier
resume_title: Desarrollador web
resume_header_intro: "Programador reconvertido desde el mundo del teatro. Aficionado a la tecnología desde mi primer 386."
resume_social:
  github: https://github.com/davidcmeier
  twitter: http://twitter.com/davidcmeier
  linkedin: https://www.linkedin.com/in/davidcmeier

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

exclude:
  - docker-compose.yml
  - Gemfile.lock
  - LICENSE
  - README.md
