# Site settings
title: "Miguel Ángel Abellán"
description: "Programador por profesión, mentor de programación por vocación."

# Resume settings
resume_name: Miguel Ángel Abellán
resume_title: Desarrollador web
resume_header_intro: "Programador por profesión, mentor de programación por vocación. Cofundador Iniciativa Programo Ergo Sum, Presidente CoderDojo España, #maker y más cosillas."
resume_social:
  github: https://github.com/migueabellan
  twitter: http://twitter.com/migueabellan
  linkedin: https://www.linkedin.com/in/migueabellan

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

